### ISSUE TITLE
CDN引入404？

### ISSUE THREAD

**Issue by ILYSHL** [dsrkafuu/sakana-widget#1]
![image](https://user-images.githubusercontent.com/42436917/186965858-771e457b-1d00-4474-8294-cd966a504a7a.png)

**Comment by shincurry** [comment]
用这个地址 `https://cdn.jsdelivr.net/npm/sakana-widget@1.1.0/lib/index.min.js`

来源 https://www.jsdelivr.com/package/npm/sakana-widget

**Comment by ILYSHL** [comment]
> 用这个地址 `https://cdn.jsdelivr.net/npm/sakana-widget@1.1.0/lib/index.min.js`
> 
> 来源 https://www.jsdelivr.com/package/npm/sakana-widget

解决了，十分感谢，已Star

**Comment by ILYSHL** [comment]
哦，还有问题···
引入后div各奔东西了，我试了几个办法好像不行。
![image](https://user-images.githubusercontent.com/42436917/186985203-e420f86d-e330-41dc-98df-5b5fcf13281d.png)
还请指导下。

**Comment by shincurry** [comment]
```html
<div id="sakana-widget" style="position: fixed; bottom: -10px; right: 20px; z-index: 999;"></div>
<script>
  function initSakanaWidget() {
    SakanaWidget({ character: 'takina' });
  }
</script>
<script
  async
  onload="initSakanaWidget()"
  src="https://cdn.jsdelivr.net/npm/sakana-widget@1.1.0/lib/index.min.js"
></script>
```

需要自己用 css 设置一下位置

**Comment by dsrkafuu** [comment]
样式/CDN路径已修复 版本`1.1.2`

**Comment by ILYSHL** [comment]
> ```
> <div id="sakana-widget" style="position: fixed; bottom: -10px; right: 20px; z-index: 999;"></div>
> <script>
>   function initSakanaWidget() {
>     SakanaWidget({ character: 'takina' });
>   }
> </script>
> <script
>   async
>   onload="initSakanaWidget()"
>   src="https://cdn.jsdelivr.net/npm/sakana-widget@1.1.0/lib/index.min.js"
> ></script>
> ```
> 
> 需要自己用 css 设置一下位置

感谢!!
