### ISSUE TITLE
TypeError: Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by rhyryy** [dsrkafuu/sakana-widget#11]
vue3中使用npm run serve时编译无异常,但该组件无法正常工作,控制台报错如下
![屏幕截图 2022-09-11 155103](https://user-images.githubusercontent.com/64307480/189517606-181fe148-649e-4690-9cba-4f04f27476dc.png)
使用build打包后能正常工作,指定serve环境为production或test时亦能正常工作,serve环境为默认项development时出现问题
使用 import SakanaWidget from 'sakana-widget'; 直接导入
或 
```
onMounted(() => {
  import('sakana-widget').then((pkg) => {
    const SakanaWidget = pkg.default
    new SakanaWidget().mount('#sakana-widget')
  });
});
```
导入均出现此错误
版本信息:
sakana-widget:2.3.0
vue:3.2.38

**Comment by dsrkafuu** [comment]
这是 Webpack 在导入 ESM 模块并同时使用 eval devtool 时出现的问题。

参考这篇文章：https://stackoverflow.com/questions/69087668/bundle-webpack-react-library-as-an-esm-module-object-defineproperty-called-on

可以通过以下这几种方法解决：

在 Webpack 配置中使用其他的 devtool 类型：

```js
const { defineConfig } = require('@vue/cli-service')
module.exports = defineConfig({
  transpileDependencies: true,
  configureWebpack: {
    devtool: 'source-map'
  }
})
```

使用 `require` 导入 CJS 版本：

```js
import HelloWorld from './components/HelloWorld.vue'
const SakanaWidget = require('sakana-widget');
```

**Comment by rhyryy** [comment]
thanks
