### ISSUE TITLE
关于自定义组件

### ISSUE THREAD

**Issue by YunJin77** [dsrkafuu/sakana-widget#5]
如果参考 README 的这一段使用说明：

```ts
const takina = SakanaWidget.getCharacter('takina');
takina.initialState = {
  ...takina.initialState,
  i: 0.001,
  d: 1,
};
SakanaWidget.registerCharacter('takina-slow', takina);
new SakanaWidget({ character: 'takina-slow' }).mount('#sakana-widget');
```

会发现切换角色后，原来的 takina 也跟着变慢了，应该不是很符合预期？

不太确定这里的 cloneDeep 用意是不是这个

https://github.com/dsrkafuu/sakana-widget/blob/0da33ae427279081d22c63087f2de928436341d9/src/index.ts#L57-L62

如果是的话，考虑设置一下 proxy？

```ts
// register default characters 
const _characters: { [key: string]: SakanaWidgetCharacter } = {};
(Object.keys(characters) as Array<keyof typeof characters>).forEach((key) => {
  const _char = characters[key];
  _characters[key] = _char;
  Object.defineProperty(_characters, key, {
    get: () => cloneDeep(_char),
  });
});
```

**Comment by dsrkafuu** [comment]
https://github.com/dsrkafuu/sakana-widget/blob/main/src/index.ts#L99-L115

我的锅，应该是这里的问题，返回角色数据的时候应该进行一次拷贝，不然后期的修改会影响原角色的数据

**Comment by dsrkafuu** [comment]
Fixed in [#bae8643](https://github.com/dsrkafuu/sakana-widget/commit/bae86432aca25a939ecf103968f04a2518c3360e)
