### ISSUE TITLE
非常棒，后续是否考虑允许用户上传图片

### ISSUE THREAD

**Issue by beebeefish** [dsrkafuu/sakana-widget#8]
用户把自己的老板或者前任头像上传进行暴力拉扯，如果有拳击🥊模式选择进行点击触碰发泄就更好了

**Comment by dsrkafuu** [comment]
自定义图片的能力目前已经有了，外部图片的加载方式还可以进一步优化下

**Comment by SSSSSSSan** [comment]
已经改成啊b的H5插件了 猛摇直播间礼物
