### ISSUE TITLE
那根棍子可以定义颜色和宽度。是否可以定义长度？

### ISSUE THREAD

**Issue by beebeefish** [dsrkafuu/sakana-widget#9]
如题

**Comment by dsrkafuu** [comment]
目前没有这个能力，组件本身容器固定是正方形的，支架的长度基于组件大小计算

**Comment by beebeefish** [comment]
谢谢您的回复。
我通过设置容器size和自定义图片缩放比例已经能够自定义调整了棍子的高度。
同时，根据原作者的音效，加了域名后面加v=xx切换用户。
也加了更多的音效，感谢您这么好的作品。

目前我已经用于我的小程序，有兴趣的话你可以看下这篇我写的文章：[https://beebee.work/2022/09/07/ikun-yao-yao-le-kong-zhi-qi-jue-ben-dai-yin-xiao/](https://beebee.work/2022/09/07/ikun-yao-yao-le-kong-zhi-qi-jue-ben-dai-yin-xiao/
)
ikun形象的摇摇乐demo:[https://cloud.enshimama.com/sakana/?v=kun](https://cloud.enshimama.com/sakana/?v=kun)

玩法介绍：  
- 用手左右拉住小人头像，放开会让小人左右晃动
- 拉扯/触摸小人会说话
- 可以切换选择音效让小人说不同的话
- 点击盒子切换小人
